/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pharmacy.views;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.pharmacy.controler.SupplierController;
import lk.ijse.pharmacy.modal.Supplier;

/**
 *
 * @author Tharaka Dasunpriya
 */
public class SupplierForm extends javax.swing.JFrame {

    /**
     * Creates new form SupplierForm
     */
    public SupplierForm() {
        initComponents();
        getAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSaddress = new javax.swing.JTextField();
        txtSname = new javax.swing.JTextField();
        txtSID = new javax.swing.JTextField();
        txtSEmail = new javax.swing.JTextField();
        txtSTele = new javax.swing.JTextField();
        txtSGov = new javax.swing.JTextField();
        btnSUpdate = new javax.swing.JButton();
        btnSAdd = new javax.swing.JButton();
        btnSDelete = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(44, 62, 80));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-product-50.png"))); // NOI18N
        jButton3.setText("DashBoard");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 110));

        jButton4.setBackground(new java.awt.Color(44, 62, 80));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-customer-50.png"))); // NOI18N
        jButton4.setText("Customer");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 200, 110));

        jButton5.setBackground(new java.awt.Color(44, 62, 80));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pills-50.png"))); // NOI18N
        jButton5.setText("Medicine");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 200, 110));

        jButton1.setBackground(new java.awt.Color(44, 62, 80));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-logout-rounded-down-48.png"))); // NOI18N
        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 790, 200, 110));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images (23).jpg"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 130));

        jButton10.setBackground(new java.awt.Color(41, 128, 185));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-procurement-50.png"))); // NOI18N
        jButton10.setText("Suppliers");
        jButton10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 200, 120));

        jButton2.setBackground(new java.awt.Color(44, 62, 80));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-supplier-50 (1)_1.png"))); // NOI18N
        jButton2.setText("Purchase");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 200, 110));

        jButton7.setBackground(new java.awt.Color(44, 62, 80));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-box-important-50.png"))); // NOI18N
        jButton7.setText("Place Order");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, 100));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 930));

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(236, 240, 241));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Supplier ID");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 160, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Supplier Name");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 160, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Supplier Address");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 160, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Supplier email");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Supplier Tele");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 160, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Supplier GOV regNO");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 160, 30));

        txtSaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaddressActionPerformed(evt);
            }
        });
        jPanel5.add(txtSaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 240, 40));

        txtSname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSnameActionPerformed(evt);
            }
        });
        jPanel5.add(txtSname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 240, 40));

        txtSID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSIDActionPerformed(evt);
            }
        });
        jPanel5.add(txtSID, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 80, 170, 40));

        txtSEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSEmailActionPerformed(evt);
            }
        });
        jPanel5.add(txtSEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 40));

        txtSTele.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSTeleActionPerformed(evt);
            }
        });
        jPanel5.add(txtSTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 240, 40));

        txtSGov.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSGov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSGovActionPerformed(evt);
            }
        });
        jPanel5.add(txtSGov, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 240, 40));

        btnSUpdate.setBackground(new java.awt.Color(230, 126, 34));
        btnSUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSUpdate.setText("Update Supplier");
        btnSUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUpdateActionPerformed(evt);
            }
        });
        jPanel5.add(btnSUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 180, 30));

        btnSAdd.setBackground(new java.awt.Color(41, 128, 185));
        btnSAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSAdd.setText("Add Supplier");
        btnSAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAddActionPerformed(evt);
            }
        });
        jPanel5.add(btnSAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 170, 30));

        btnSDelete.setBackground(new java.awt.Color(192, 57, 43));
        btnSDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSDelete.setText("Delete Supplier");
        btnSDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btnSDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 190, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 900, 330));

        jPanel8.setBackground(new java.awt.Color(41, 128, 185));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Suppliers Form");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 280, 30));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 810, 60));

        jPanel4.setBackground(new java.awt.Color(236, 240, 241));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/survival-bag.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 100, 60));

        jLabel2.setBackground(new java.awt.Color(52, 152, 219));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Chamara");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 130, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pharmacy-shop-50 (1)_1.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 60, 80));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Pharmacy Managment System");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 410, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ph black.png"))); // NOI18N
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 240, 150));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 920, 160));

        jPanel6.setBackground(new java.awt.Color(236, 240, 241));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSupplier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SupplierID", "SupplierName", "SupplierAddress", "SupplierEmail", "SuppliereTele", "SupplierGOVregNo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupplier);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 20, 690, 190));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 850, 230));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1050, 930));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1251, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         new DashBoardForm().setVisible(true);
        this.dispose();

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new CustomerForm().setVisible(true);
      this.dispose();

        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new MedicineForm().setVisible(true);
        this.dispose();

        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new newLoginForm().setVisible(true);
       this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaddressActionPerformed

    private void txtSnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSnameActionPerformed

    private void txtSIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSIDActionPerformed
         if(txtSID.getText().trim().length()>0){
             try {
                 Supplier OBJ=new SupplierController().getSupplierAdd(txtSID.getText().trim());
                 
                 
                 if(OBJ!=null){
                     txtSID.setText(OBJ.getSupplier_id());
                     txtSname.setText(OBJ.getSupplier_name());
                     txtSaddress.setText(OBJ.getSupplier_address());
                     txtSEmail.setText(OBJ.getSupplier_email());
                     txtSTele.setText(OBJ.getSupplier_tele().toString());
                     txtSGov.setText(OBJ.getSupplier_regNo());
                     
                     
                 }else{
                     JOptionPane.showMessageDialog(this, "No results Found","Warning",JOptionPane.WARNING_MESSAGE);
                 }
             } catch (ClassNotFoundException | SQLException ex) {
                 Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
             }
         }else{
            JOptionPane.showMessageDialog(this, "Please Insert an ID","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_txtSIDActionPerformed

    private void txtSEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSEmailActionPerformed

    private void txtSTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSTeleActionPerformed

    private void txtSGovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSGovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSGovActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       
    }//GEN-LAST:event_formWindowClosed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         new purchaseForm().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAddActionPerformed
        try {
            String SID=txtSID.getText();
            String Sname =txtSname.getText();
            String Saddress=txtSaddress.getText();
            String Semail=txtSEmail.getText();
            Integer Stele = Integer.parseInt(txtSTele.getText());
         
            String Sgov=txtSGov.getText();
            
            Supplier s1=new Supplier(
                    SID,
                    Sname,
                    Saddress,
                    Semail,
                    Stele,
                    Sgov
                    
            );
            boolean isSaved=new SupplierController().saveSupplier(s1);
            if(isSaved){
                JOptionPane.showMessageDialog(null, "Saved");
                   DefaultTableModel dtm = (DefaultTableModel)tblSupplier.getModel();
				Object[] rowData = {
					s1.getSupplier_id(),
                                    s1.getSupplier_name(),
                                    s1.getSupplier_address(),
                                    s1.getSupplier_email(),
                                    s1.getSupplier_tele(),
                                    s1.getSupplier_regNo(),
				};
				dtm.addRow(rowData);
				txtSID.setText(null);
				txtSname.setText(null);
				txtSaddress.setText(null);
				txtSEmail.setText(null);
				txtSTele.setText(null);
                                txtSGov.setText(null);
                                
            }else{
                JOptionPane.showMessageDialog(null, "Try again");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
            
        
        
        
        
    }//GEN-LAST:event_btnSAddActionPerformed

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
     int selectedRow = tblSupplier.getSelectedRow();
		txtSID.setText(tblSupplier.getValueAt(selectedRow, 0).toString());
		txtSname.setText(tblSupplier.getValueAt(selectedRow, 1).toString());
		txtSaddress.setText(tblSupplier.getValueAt(selectedRow, 2).toString());
		txtSEmail.setText(tblSupplier.getValueAt(selectedRow, 3).toString());
		txtSTele.setText(tblSupplier.getValueAt(selectedRow, 4).toString());
		txtSGov.setText(tblSupplier.getValueAt(selectedRow, 5).toString());  
        
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void btnSDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSDeleteActionPerformed
       if(txtSID.getText().trim().length()>0){  
           try {
               if (new SupplierController().dropSupplier(txtSID.getText().trim())) {
                   JOptionPane.showMessageDialog(null,"Deletetd...");
                   getAll();
               }else{
                   JOptionPane.showMessageDialog(null,"Something went Wrong!!!", "WARNING",JOptionPane.WARNING_MESSAGE);
               }
           } catch (ClassNotFoundException | SQLException ex) {
               Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
           }
        }else{
            JOptionPane.showMessageDialog(null, "Please Insert an ID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnSDeleteActionPerformed

    private void btnSUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUpdateActionPerformed
        if(txtSID.getText().trim().length()>0){
            try {
                String SID=txtSID.getText();
                String Sname =txtSname.getText();
                String Saddress=txtSaddress.getText();
                String Semail=txtSEmail.getText();
                Integer Stele = Integer.parseInt(txtSTele.getText());
                
                String Sgov=txtSGov.getText();
                
                Supplier s1=new Supplier(
                        SID,
                        Sname,
                        Saddress,
                        Semail,
                        Stele,
                        Sgov
                        
                );   if(new SupplierController().updateState(s1)){
                    JOptionPane.showMessageDialog(null,"Done...");
                    getAll();
                }else{
                    JOptionPane.showMessageDialog(null,"Please Try Again","WARNING",JOptionPane.WARNING_MESSAGE);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
            }
             }else{
            JOptionPane.showMessageDialog(null,"Please Insert an ID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSUpdateActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
          new CustomerPlaceOrderForm().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSAdd;
    private javax.swing.JButton btnSDelete;
    private javax.swing.JButton btnSUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtSEmail;
    private javax.swing.JTextField txtSGov;
    private javax.swing.JTextField txtSID;
    private javax.swing.JTextField txtSTele;
    private javax.swing.JTextField txtSaddress;
    private javax.swing.JTextField txtSname;
    // End of variables declaration//GEN-END:variables

    private void getAll() {
        try {
            ArrayList<Supplier> allsuppliers = SupplierController.getAllSuppliers();
            DefaultTableModel dtm = (DefaultTableModel)tblSupplier.getModel();
            dtm.setRowCount(0);
            for (Supplier s1: allsuppliers) {
                Object[] rowData = {
                    s1.getSupplier_id(),
                    s1.getSupplier_name(),
                    s1.getSupplier_address(),
                    s1.getSupplier_email(),
                    s1.getSupplier_tele(),
                    s1.getSupplier_regNo()};
                dtm.addRow(rowData);
                
            }   } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SupplierForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
